name: Test Generate Files

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Run test-generate-files.sh
        run: |
          chmod +x tests/test-generate-files.sh
          cd ./tests/
          ./test-generate-files.sh